config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :purchases
  resources :concerts
  resources :user_sessions
  resources :users

 root 'concerts#index'

 get "login", :to => "user_sessions#new"
get "logout", :to => "user_sessions#destroy"

get 'concert_purchase/:concert_id/new' => 'purchases#new', as: :concert_purchase

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'concerts', :to => 'concerts#index'
    get 'concerts/:id', :to => 'concerts#show'
  end
end

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'venues', :to => 'venues#index'
    get 'venues/:id', :to => 'venues#show'
  end
end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  load_and_authorize_resource
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    if current_user.has_role? :admin
      @purchases = Purchase.all
    else
      @purchases = current_user.purchases
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
    @concert = Concert.find(params[:concert_id])
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user
    @purchase.concert_id = purchase_params[:concert_id]
    @purchase.payment_amount = (@purchase.ticket_quantity * @purchase.payment_amount)
    respond_to do |format|
      if @purchase.save
        if @purchase.make_transaction
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        @concert = Concert.find(@purchase.concert_id)
          @purchase.destroy
          format.html { redirect_to @concert, :flash =>  { :error => 'Purchase failed.'} }
        end
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:ticket_quantity, :payment_amount, :response, :concert_id, :first_name, :last_name, :card_number, :card_expiry)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= @concert.name  %> Concert</h3>

  <%= f.hidden_field(:concert_id, :value => @concert.id) %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :ticket_quantity %><br>
    <%= f.number_field :ticket_quantity %>
  </div>
  <div class="field">
    <%= f.label :payment_amount %><br>
    <%= f.text_field :payment_amount, :value => number_with_precision(@concert.price, precision: 2), :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br>
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_expiry %><br>
    <%= f.date_select :card_expiry, :discard_day => true, :start_year => Date.today.year+2, :end_year => Date.today.year+12, :use_month_numbers => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table class="table">
  <thead>
    <tr>
      <th>Ticket quantity</th>
      <th>Payment amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.ticket_quantity %></td>
        <td><%= number_to_currency(purchase.payment_amount) %></td>
        <td><%= link_to 'Show', purchase, :class=>"btn btn-info" %></td>

        <% if can? :manage, purchase %>
        <td><%= link_to 'New Purchase', new_purchase_path, :class=>"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket quantity:</strong>
  <%= @purchase.ticket_quantity %>
</p>

<p>
  <strong>Payment amount:</strong>
  <%= number_to_currency(@purchase.payment_amount) %>
</p>

<p>
  <strong>Response:</strong>
  <%= @purchase.response %>
</p>

<%= link_to 'Back', purchases_path %>

<% if can? :manage, @purchase %>
<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<% end %>