config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :purchases
  resources :concerts
  resources :user_sessions
  resources :users

 root 'concerts#index'

 get "login", :to => "user_sessions#new"
get "logout", :to => "user_sessions#destroy"

get 'concert_purchase/:concert_id/new' => 'purchases#new', as: :concert_purchase

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'concerts', :to => 'concerts#index'
    get 'concerts/:id', :to => 'concerts#show'
  end
end

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'venues', :to => 'venues#index'
    get 'venues/:id', :to => 'venues#show'
  end
end

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  has_many :concerts

  

end

app/controllers/api/v1/venues_controller.rb
module Api
  module V1

    class VenuesController < ApplicationController
      respond_to :json

      def index
        @venues = Venue.all
      end

      def show
        @venue = Venue.find(venue_params[:id])
      end

      private
      def venue_params
        params.permit(:id)
      end

    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

load_and_authorize_resource

  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :address, :city, :state, :zip)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, :class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, :class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state, :class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, :class =>"form-control" %>
  </div>
</div>
  <div class="actions">
    <%= f.submit :class =>"btn btn-success btn-round" %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue, :class =>"btn btn-primary btn-sm" %> |
<%= link_to 'Back', venues_path, :class =>"btn btn-primary btn-sm" %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= venue.address %></td>
        <td><%= venue.city %></td>
        <td><%= venue.state %></td>
        <td><%= venue.zip %></td>
        <td><%= link_to 'Show', venue, :class=>"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue), :class=>"btn btn-warning"  %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path,:class =>"btn btn-default btn-round" %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @venue.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @venue.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @venue.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @venue.zip %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>