config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :purchases
  resources :concerts
  resources :user_sessions
  resources :users

 root 'concerts#index'

 get "login", :to => "user_sessions#new"
get "logout", :to => "user_sessions#destroy"

get 'concert_purchase/:concert_id/new' => 'purchases#new', as: :concert_purchase

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'concerts', :to => 'concerts#index'
    get 'concerts/:id', :to => 'concerts#show'
  end
end

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'venues', :to => 'venues#index'
    get 'venues/:id', :to => 'venues#show'
  end
end

end

app/models/concert.rb
class Concert < ActiveRecord::Base

  has_many :purchases

  belongs_to :venue

  def tickets_remaining
    a = self.tickets_available
    b = self.purchases.sum(:ticket_quantity)
    return a-b
  end

  def tickets_percentage
    a = self.tickets_available
    b = tickets_remaining
    return (b.to_f / a.to_f) * 100
  end

end

app/controllers/api/v1/concerts_controller.rb
module Api
  module V1

    class ConcertsController < ApplicationController
      respond_to :json

      def index
        @concerts = Concert.all
      end

      def show
        @concert = Concert.find(concert_params[:id])
      end

      private
      def concert_params
        params.permit(:id)
      end

    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController


  load_and_authorize_resource
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:name, :start_date, :end_date, :price, :tickets_available, :venue_id, :venue)
    end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date, :class => "btn btn-simple dropdown-toggle" %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date, :class => "btn btn-simple dropdown-toggle" %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :tickets_available %><br>
    <%= f.number_field :tickets_available, :class =>"form-control" %>
  </div>
  <div class="field">
  <%= f.label :venue %><br>
  <%= f.collection_select :venue_id, Venue.all.collect, :id, :name, {:include_blank => "Select Venue"} %>
</div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concerts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Price</th>
      <th>Tickets available</th>
      <th>Venue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.name %></td>
        <td><%= concert.start_date %></td>
        <td><%= concert.end_date %></td>
        <td><%= number_to_currency(concert.price) %></td>
        <% if concert.tickets_percentage < 21 && concert.tickets_remaining != 0 %>
        <td class="warning"><%= concert.tickets_remaining %></td>
        <% end %>

        <% if concert.tickets_remaining == 0 %>
        <td class="danger"><%= concert.tickets_remaining %></td>
        <% end %>

        <% if concert.tickets_percentage > 21 %>
        <td><%= concert.tickets_remaining %></td>
        <% end %>

        <td><%= concert.venue.name if concert.venue %></td>

          <% if current_user %>
          <% if current_user.has_role? :customer %>
          <td><%= link_to 'Concert Details', concert, :class=>"btn btn-info" %></td>
          <% end %>
          <% end %>

          <% if can? :manage, concert %>
            <td><%= link_to 'Show', concert, :class=>"btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_concert_path(concert), :class=>"btn btn-warning" %></td>
            <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path,:class =>"btn btn-default btn-round" %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @concert.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @concert.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @concert.end_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@concert.price) %>
</p>

<p>
  <strong>Tickets available:</strong>
  <%= @concert.tickets_remaining %>
</p>
<p>
  <strong>Venue:</strong>
  <%= @concert.venue.name if @concert.venue %> |

  <% if @concert.tickets_remaining == 0 %>
<p><strong>CONCERT SOLD OUT!</strong></p>
<% else %>

<% if current_user %>
<% if current_user.has_role? :admin %>
<td><%= link_to 'Venue Details', venue_path(@concert.venue) %></td>
<% end %>
<% end %>
</p>

<% if current_user %>
  <% if current_user.has_role? :customer %>
    <p><%= link_to 'Purchase', concert_purchase_path(@concert.id), :class => "btn btn-primary" %></p>
  <% end %>
<% else %>
  <p>
  <strong>You must be registered and logged in to purchase tickets.</strong>
  </p>
<% end %>

<% if current_user %>
<% if current_user.has_role? :admin %>
<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>
<% end %>
<% end %>
<% end %>