config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :purchases
  resources :concerts
  resources :user_sessions
  resources :users

 root 'concerts#index'

 get "login", :to => "user_sessions#new"
get "logout", :to => "user_sessions#destroy"

get 'concert_purchase/:concert_id/new' => 'purchases#new', as: :concert_purchase

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'concerts', :to => 'concerts#index'
    get 'concerts/:id', :to => 'concerts#show'
  end
end

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'venues', :to => 'venues#index'
    get 'venues/:id', :to => 'venues#show'
  end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertTickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
    	<div class="navbar-header">
    		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
    		</button>
    		<a class="navbar-brand" href="#">E-Ticket</a>
    	</div>

    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    		<ul class="nav navbar-nav">
				<li><%= link_to("Home", root_url) %></li>
        <li> <%= link_to("Concerts", concerts_path) %> </li>


              <% if current_user %>
              <% if current_user.has_role? :admin %>
                <li><%= link_to("Venues", venues_path) %> </li>
              <% end %>
              <% end %>

              <% if current_user %>
              <% if current_user.has_role? :admin %>
                <li> <%= link_to("Users", users_path) %> </li>
              <% end %>
              <% end %>

              <% if current_user %>
                <li><%= link_to("View Purchases", purchases_path(current_user)) %></li>
                <li><%= link_to("Edit Profile", edit_user_path(current_user)) %> </li>
                <li><%= link_to("Logout", logout_path) %> </li>
              <% else %>
                <li><%= link_to("Register", new_user_path) %> </li>
                <li><%= link_to("Login", login_path) %> </li>
              <% end %>
            	</ul>
    	</div>
	</div>
</nav>


<div class="container">
  <div class="row">


<%= yield %>

</div>
</div>

</body>
</html>